### ISSUE TITLE
[Proposal] Message content negotiation

### ISSUE THREAD

**Issue by mxgrey** [eProsima/Integration-Service#1]
An issue that @koonpeng and I have come across in SOSSv2 is that a lot of unspoken trust is being currently being placed on the middleware plugins to format each `soss::Message` in perfect agreement with each other, despite no formal way for them to communicate with each other about what content they're each expecting in their plugins.

The message container that moves between the middlewares (currently `soss::Message`, but probably an [xtype](https://www.omg.org/spec/DDS-XTypes/About-DDS-XTypes/) in the future) is completely dynamic and flexible by design. It can accommodate whatever kind of message content the plugins want. Furthermore, the middleware plugins can use introspection on the generic message objects to figure out what content they can extract from the message.

I was reluctant to have the currently supported middlewares (`soss-ros1`, `soss-ros2`, `soss-websocket`) use message inspection at runtime, because I felt it would add unnecessary map lookup overhead to the process of passing each and every message. ROS1 and ROS2 both have statically defined message structures, so there's no need to verify the message content that's being passed between them. And then for `soss-websocket`, I felt it wasn't too burdensome to just make sure the remote endpoint was passing correctly formatted messages.

However, this poses a problem as we try to support more and more middlewares. Some middlewares may have more dynamic message structures, which we should still try to support somehow. We could place the burden on each middleware to inspect their incoming messages, but I think that adds unnecessary runtime overhead, and I think we can do better.

### So here's my proposal

During the configuration stage, before soss begins passing messages between middlewares, we can have a "message content negotiation" phase. Imagine the following data structures (this is just a rough sketch):

```
struct FieldExpectation
{
  // expresses what kind of type is expected
  TypeInfo type;
  
  // true if this field is absolutely required and MUST be
  // present in the soss::Message. Statically typed
  // middlewares can set this to true to avoid any runtime
  // introspection.
  bool required;

  // true if it is okay to fill this field with a default value
  // when the upstream middleware left the field blank.
  // If required is true while default_allowed is false,
  // the message must be dropped if the upstream 
  // middleware left the field blank.
  bool default_allowed;

  // If a default is allowed, this is the value it should contain.
  // If this is unspecified while default_allowed is true, then
  // the default value can be anything.
  std::optional<Value> default_value;

  // If this field contains a message type, then this will contain
  // the expectation of that nested message.
  std::unique_ptr<MessageExpectation> 
};

struct MessageExpectation
{
  // A map from field name to the expectations for that field
  std::map<std::string, FieldExpectation> fields;
};
```

While configuring the middlewares, each middleware plugin would pass back their `MessageExpectation` (one per publisher/subscriber, and two per service/client). The soss instance would then aggregate their expectations so that the most strict expectation wins (e.g. if any middleware sets a field to `required`, then that field will be considered required, even if the other middlewares don't require it). If there are any irreconcilable conflicts in expectations (e.g. one middleware expects a field to be a `float` while another middleware expects a `std::string`), then the configuration will fail and the soss executable will quit without ever passing any messages.

After the expectations are aggregated, each middleware plugin will be informed of the final message expectation for each of their publishers, subscribers, service providers, and clients. Each middleware can then inspect each expectation, and then either affirm or reject their ability to support the expectation. If any middleware rejects any of the expectations, then the soss instance will quit right away.

@JBurgos-eProsima , I know there's interest in replacing `soss::Message` with DDS xtypes. Does this concept of message structure negotiation exist already for xtypes? I haven't had a chance to familiarize myself with the specification yet. Either way I imagine we can build this concept on top of xtypes, but it would be neat if it already exists.

**Comment by koonpeng** [comment]
I'm not sure if this will solve the issue though, the middlewares wont know the other side's expectations until runtime, so we still can't make any guarantee between any 2 middlewares.

If I want my middleware to be compatible to as many other middlewares as possible, I will need to make it support the most restrictive option, and given the goal of SOSS is cross-protocol/middleware compatibility, it sort of makes it the unofficial SOSS "requirements".

In the end, this only test compatibility between 2 middlewares, but doesn't provide any system to ensure compatibility.

**Comment by mxgrey** [comment]
My take is that we should allow middlewares to be strict if they need to be strict. By implementing a very strict middleware plugin, the author is saying "I understand that I'm restricting the other middlewares that I may be able to communicate with, but these requirements are important to me."

If middlewares want to be more flexible, then they can just set their `required` flags to false for all their fields. Then they'll have no trouble talking with any other similarly flexible middleware plugin, at the cost of additional runtime overhead as they need to inspect each incoming message to identify what fields it has available.

I think strictness is also something we can allow users to configure in the `soss.yaml` file. For example (rough idea):

```
systems:
  ros1: { type: ros1, expectations: loose }
  ros2: { type: ros2, expectations: strict }
# ....
```

The `loose` setting would maximize compatibility with other middleware plugins at the cost of runtime overhead. The `strict` setting would limit compatibility with other middleware plugins but allow the plugin to maximize runtime performance and provide guarantees that upstream messages are well-formed.

**Comment by koonpeng** [comment]
> If middlewares want to be more flexible, then they can just set their required flags to false for all their fields. Then they'll have no trouble talking with any other similarly flexible middleware plugin, at the cost of additional runtime overhead as they need to inspect each incoming message to identify what fields it has available.

If middleware A says a certain field is `required` but middleware B says its not, then by default, middleware A wins, and then if the field is not available what can middleware B do? E.g. for `int` it can add a dummy value `0`, but how can it convey that its not an actual `0` but a value to say `missing`. From A's point of view, its `required` so it would just read `0` as is, this totally messes up the data contract between the 2 middlewares.

And since expectation required `false` is to also supposed to work with required `true`, now each middleware must have code to handle the situation where a message negotation ends with required `true`, and the only way it can do this is through runtime introspection, so this system wouldn't even remove the need for it.

Even with strictness setting, it doesn't make middleware's compatible, I could set both middlewares to `loose` and I would still have no idea if they will work with each other.

**Comment by mxgrey** [comment]
I think I addressed these points in the original explanation, but admittedly it's hard to convey it all through raw text. I should see about drawing up diagrams if we decide to move forward with this proposal. I'll try to address your concerns explicitly below, and you can let me know if I'm still overlooking something:

> If middleware A says a certain field is required but middleware B says its not, then by default, middleware A wins

Yes.

> and then if the field is not available what can middleware B do?

If middleware A says that `default_allowed` is true, then middleware B can fill in that field with `default_value` if the `default_value` is provided (if `default_value` is not provided, then middleware B can fill the field with anything, although I don't expect this to be a common case). If `default_allowed` is false, then I think we need to make a design choice. Either:

1. Configuration fails and the soss executable quits immediately
2. Upstream messages that are missing the required field get dropped during runtime

I don't know which behavior is better. Maybe we need an additional flag in the expectation specification to decide between these two options?

> E.g. for int it can add a dummy value 0, but how can it convey that its not an actual 0 but a value to say missing. From A's point of view, its required so it would just read 0 as is, this totally messes up the data contract between the 2 middlewares.

It cannot, which is why we would have the `default_allowed` flag.

> And since expectation required false is to also supposed to work with required true, now each middleware must have code to handle the situation where a message negotation ends with required true

I don't see why middlewares that permit optional fields would need to do anything differently if all (or any) fields become required. Unless you mean dynamic-type publishers need to do one extra check to see if it's missing any required fields and then fill in that field with a default if it's missing? But I think that's easily accomplished by always starting from a message instance where required fields are initialized with their default values. Then if those fields are missing from the upstream middleware, they just get sent along through soss with their default values.

> and the only way it can do this is through runtime introspection, so this system wouldn't even remove the need for it.

It can remove the need for runtime introspection for any middlewares which declare all their fields as required. Middlewares which were dynamically typed to begin with will need to do introspection regardless, so I don't see any loss there.

> Even with strictness setting, it doesn't make middleware's compatible, I could set both middlewares to loose and I would still have no idea if they will work with each other.

I think middleware compatibility will ultimately need to be something that's documented somewhere. I don't think it's reasonable to try to guarantee that all possible middlewares will be compatible for all possible use cases. At least with this "expectations" scheme, the middlewares can talk to each other during startup to determine if they'll be compatible, and if they're not compatible then they can tell you why and exit immediately.

**Comment by mxgrey** [comment]
> E.g. for int it can add a dummy value 0, but how can it convey that its not an actual 0 but a value to say missing. From A's point of view, its required so it would just read 0 as is, this totally messes up the data contract between the 2 middlewares.

Although come to think of it, I wouldn't be against giving the `soss::Field` class some additional flag to communicate whether or not it's containing a default value. I don't know if there's something analogous in xtypes.

**Comment by koonpeng** [comment]
sometimes there is a difference between "default value" and "not available", and sometimes the middleware doesn't know what is the "default value" either, e.g. a rest client, which receive response from a server which contains an optional field which may not be there, it doesn't know what is a suitable "default". Then of course, if `default_allowed` is false, the middlewares are just incompatible now.

I agree this scheme does help the middleware to check if they are compatible, but it doesn't give any guidelines what kind of expectation levels a middleware should have, and I agree it does help for middlewares that follows similar expectation schemes. I would propose perhaps a "strict" mode where 2 compatible middlewares can talk to each other with the same expectation schemes, and a "loose" mode where the middleware must follow some kind of official SOSS guidelines/expectation scheme.

**Comment by mxgrey** [comment]
Yeah, there are definitely loose ends here that need to be tied up, and it's really not obvious what the "right" behavior should be in many conceivable cases.

In my mind, the critical goals for the "negotiation scheme" are:

1. Allow middleware plugins to talk to each other about what they expect for the content of messages
2. Allow them to come to a consensus on their expectations when possible
3. Quit immediately if a consensus is not possible, and explain to the user what the conflict is

If, in addition to that, we can come up with easily configurable options to help end users get the exact behavior that they desire, then that would be a huge win.

Admittedly this still leaves an awful lot of heavy lifting for the middleware plugin implementers, but it should at least be better than the wild wild west situation we have at the moment where there aren't really any explicit contracts at all between the plugins. Hopefully we can concentrate a lot of the heavy lifting into generic utilities inside of the `soss-core` library (e.g. functions for recursively initializing a `soss::Message` with any required fields).

**Comment by koonpeng** [comment]
I took a quick look at the DDS xtypes specification, it does have clear rules about message formats, things like key names, type inheritance, how to send send from derived type to base type and vice versa, heterogeneous arrays etc.

I think that SOSS does need some kind of specification like this, I don't think the proposed expectation scheme will be enough, it encourages middlewares to stick to their native expectations and if the other side don't conform to the same expectation, they simply can't talk.

As an example, ros2 key names can't have hypen '-', while its totally fine in json (also things like unicodes in key names). Under the expectation scheme, the rest middleware can't possibly know what the other side's expectations are, what if there is another middleware that allows '-' but not '_'. Given that the most restrictive wins, ALL middlewares must now handle all scenarios across all possible middleware's expectations else they simply won't be able to talk to each other, the idea of SOSS is to translate messages across different protocols and I don't think this scheme can achieve that.

Another example, what if one particular middleware has max message length of say 255, now all middlewares who want to talk to it must implement fragmentation (since most restrictive wins), it makes more sense that the one particular middleware implementation fragmentation and it can now talk to any other middlewares out there. For the ros2<->json example above, it makes more sense for the ros2 middleware to implement some kind of encoding scheme to transmit key names with '-', instead of expecting all other middlewares to stop sending '-' keys. For this to work, I think we do need some kind of specification like xtypes/json/yaml or even ros2 that all middlewares should conform to.

**Comment by mxgrey** [comment]
> Under the expectation scheme, the rest middleware can't possibly know what the other side's expectations are

You mean it can't know at compile time? Because the whole point is that the expectations can always be revealed at runtime. It should be entirely possible to have middleware plugins dynamically reconfigure themselves at runtime to deal with various possible expectations from other middlewares.

> what if there is another middleware that allows '-' but not '_'.

I think this specific problem is somewhat ill-defined, because what happens in the pathological case where a message has a field `with-this-name` and then another field `with_this_name` as different fields? Granted, that would be absolutely atrocious design, but I think it illustrates that this kind of behavior is something that users, not implementers, need to have control over.

If someone is trying to talk across middlewares without a clear mapping between the message definitions, then they have an ill-defined configuration. eProsima talked about allowing users to specify "transform" plugins which would be functions that perform a transformation from one side's message representation to the other side's. I think for cases where there isn't an obvious mapping, users should have to either specify either a transform plugin or maybe specify the mapping in the configuration, e.g.:

```
message_remap:
  my_remapping:
    "field-name": { ros2: "field_name" }
    "another_field-name": { ros2: "another_field_name" }

topics:
  my_topic: { type: "my_package/my_type", route: web_to_ros2, message_remap: my_remapping }
```

**Comment by koonpeng** [comment]
I see the requirement for a transform plugin a design flaw though, instead of a 1 to N pattern where you just right 1 middleware and it can talk to every other middlewares out there, now in the worst case, you need a 1 to 1 pattern for each transformation plugin.

I think I have said my opinions about needing standardization, this being quite a huge design consideration for SOSSv3, should we gather more feedback from other people?

**Comment by mxgrey** [comment]
I think having clear, easy ways for users to configure message transformations is still a huge improvement over a sossless world where you have to implement entire endpoints from scratch (and still have to implement transformations yourself) whenever you want two independent middlewares to talk to each other.

I guess I'm not clear on what exactly you mean by "standardization" or "specification" in this context, and so I don't have a good grasp on how it would solve arbitrary conflicts between the differing constraints of arbitrary middlewares.

**Comment by koonpeng** [comment]
A good example would be DDS xtypes specification https://www.omg.org/spec/DDS-XTypes/1.3/Beta1/PDF. It define things like primitive data types, array bounds, heterogeneous arrays and many other things. Without these definitions, each middleware just does its own thing and other middlewares do not know how to interact with it. This expectation proposal only serve to validate compatibility at runtime, middlewares still dont know what kind of expectation it should be prepared to handle.

I think the message length limit example gives a good overview of my argument, even if right now we get ros1/ros2/websockets/rest to work with each other with some transformation plugins, if we add a 5th middleware 'X' that has max length limit, it can't talk to any of the 4 existing middlewares, and under this expectation proposal, all the 4 middlewares would have to implement fragmenting its messages. With a standards/rule that say messages should not have length limit, now it becomes middleware 'X''s role to implement fragmentation and we only need to do so in 1 middleware for all 5 middlewares to be able to talk to each other.

**Comment by mxgrey** [comment]
Thanks, that helps me understand your specific concern. I think that issue specifically can mostly be resolved by replacing `soss::Message` with xtypes.

I imagine we'll still need transformation plugins/configurations to deal with inconsistencies between middleware limitations.

**Comment by koonpeng** [comment]
Yes, looks like I finally get my concerns acrossed. It doesn't necessarily have to be xtypes though, we can base off other message formats like json/yaml/ros2, or even create our own.

Yeah, there will always be edge cases where some middlewares just straight up can't support the message format soss::Message decides to use. We should only have to use these transformation plugin only under these edge cases, my concern is that without any kind of conformance guidelines, these edge cases will become the norm as every middleware expects the other side to support the same expectation schemes it uses.

The conformance guidelines makes it clear if a middleware needs to do any kind of pre/post processing to avoid reliance on transformation plugins everytime.

**Comment by BorjaOuterelo** [comment]
Hi, @mxgrey, @koonpeng.

DDS-XTypes specification could help here with the usage of TypeObjects, TypeIdentifiers and TypeInformation. Comparing them in addition to the rules defined in the QoS will address type matching issues.

Here is a list of interesting references inside the DDS-Xtypes specification:
Sección 7.6.3 Discovery and Endpoint Matching

- 7.6.3.1 Data Representation. 

- 7.6.3.3 Discovery Built-in Topics. If we don't know the type, try to get its information from the other end, using TypeObject or TypeLookup Service(7.6.3.3.4).

- 7.6.3.4 TypeConsistencyEnforcement. I think this is more appealing in the case of type compatibility and restriction handling making types compatible or checking if possible. 7.6.3.4.1 has more details.

Ideally using TypeObject to compare compatible types could provide a solution to validate  compatible communications. Additionally, transformation libraries could make this comparison more flexible. So if two TypeObjects are mismatching but you can fix those mismatching points using a transformation library.

I think it could be great if we can join efforts here and como up with a good design.

**Comment by jamoralp** [comment]
Closed since now [eProsima xTypes](https://github.com/eProsima/xtypes) is the common language used to speak to the core.
