### ISSUE TITLE
Unable to colcon build soss-dds

### ISSUE THREAD

**Issue by destkk** [eProsima/Integration-Service#113]
Ubuntu: 20.04

Hi there. I have followed the intial method to install SOSS. After which I have git clone the SOSS-DDS into the soss-workspace.
I have received the following error below thus uanble to colcon build it.

Does anyone have a solution for this issue?

```
Starting >>> soss-core
Finished <<< soss-core [0.13s]                     
Starting >>> soss-dds
--- stderr: soss-dds                         
CMake Error at CMakeLists.txt:35 (add_subdirectory):
  The source directory

    /home/soss-workspace/src/soss-dds/dds/thirdparty/fastrtps

  does not contain a CMakeLists.txt file.


---
Failed   <<< soss-dds [0.34s, exited with code 1]

Summary: 1 package finished [0.60s]
  1 package failed: soss-dds
  1 package had stderr output: soss-dds

```

**Comment by jamoralp** [comment]
Good morning,

Closing this, since inactive for almost three months. Please, do not hesitate to reopen this issue if any problem arises again. Thank you!
