### ISSUE TITLE
Segmentaion fault

### ISSUE THREAD

**Issue by golizheh** [eProsima/Integration-Service#125]
Hi,

I just have a question regarding communication between Fastrps in one computer and ROS2 in another computer. 
I have used YAML file sample directory:
systems:
    dds:
      type: dds
      dynamic types:
        struct std_msgs__String:
          string: "data"

    ros2:
      type: ros2

routes:
    ros2_to_dds: { from: ros2, to: dds }
    dds_to_ros2: { from: dds, to: ros2 }

topics:
    hello_ros2: { type: "std_msgs/String", route: dds_to_ros2 }
    hello_dds: { type: "std_msgs/String", route: ros2_to_dds }

and when I run: soss dds_ros2.yaml
I have get an error : segmentaion fault (core dumped)

As it is shown in the document which is attahced I have following setup and I want to transfer message between fastrtps and ROS2 (For starting point let say both are in the same machine)
[example.docx](https://github.com/eProsima/SOSS-DDS/files/3728894/example.docx)

Could you please provide me some help in this issue?

**Comment by lemunozm** [comment]
`soss-dds` is not executable, it is a dynamic library that `soss` application will load at runtime, depending on your configuration file. You always need to run `soss configuration_file.yaml`.

Please, tell me which commit of SOSS are you using in order to help you. Maybe the `soss-dds` plugin version and the soss application you are using are not compatible. To ensure this, please, install soss from this commit: https://github.com/osrf/soss/tree/660078e9fee9fca1b3094d62dc6a22d4a1e80a38

**Comment by golizheh** [comment]
Dear @lemunozm 
I have install soss from https://github.com/eProsima/SOSS-DDS. 
I have follow the page step by step  and finally I have run:
soss dds_ros2.yaml 
which I will get  Segmentaion fault  error.
I just want to have a communication between ROS2 and FastRTPS in my computer. (Let say communication between ROS2 and DDS Cloud in my local computer)

Now I have to reinstall everything from https://github.com/osrf/soss/tree/660078e9fee9fca1b3094d62dc6a22d4a1e80a38 ??

Thanks in advance 
Look forward to hearing from you

**Comment by lemunozm** [comment]
Hi @golizheh,
In the step two: you have done `git clone https://github.com/osrf/soss_v2.git src/soss`.
This, cloned the **last version** soss main project to a folder `src/soss`. The soss-dds plugin only works if the **version of soss is under** the `660078e9fee9fca1b3094d62dc6a22d4a1e80a38` commit. Your problem could come from this incompatibility.
To ensure your compatibility, please, navigate to `src/soss` and execute `git checkout 660078e9fee9fca1b3094d62dc6a22d4a1e80a38`. Then, build again you workspace.

I hope this could fix your problem.

Another problem could be the FastRTPS version, did you have already installed fastrtps?
