### ISSUE TITLE
ROS2 and DDS ,UDP communication in TWO different PC

### ISSUE THREAD

**Issue by golizheh** [eProsima/Integration-Service#127]
Hi,

Could you please provide a helloworld example of using soss-DDS? If in PC1 we  have FASTRTPS which is runs Hellowrold example and in the PC2 we have ROS2 which is runs Talker.
PC2 Run:ROS2 Talker/Listener example.
PC1 Run: Fast RTPS HelloWorld example.
And we also have ross  for communication between this two.(YAML files and topics)

I think it is makes job much more clear.
Thanks for your help
With Best Regards

**Comment by lemunozm** [comment]
Hi @golizheh, 
I think that the hello world example you are looking for can be found at sample folder: https://github.com/eProsima/SOSS-DDS/blob/master/dds/sample/udp/dds_ros2.yaml
This is the yaml required in order to enable the communication between dds and ros2.

Regards.
