### ISSUE TITLE
[Question] Modifying QOS in WAN communication

### ISSUE THREAD

**Issue by ruimscarvalho98** [eProsima/Integration-Service#153]
Hello there,

I apologize if this is not the best place to make these type of questions.

I was trying to use the WAN communication example to connect to a remote server using ROS2, but some of the topics I want to publish to the server have BEST_EFFORT reliability whereas the ros2 subscribers/publishers created by the example are RELIABLE by default making them incompatible. 

Is there any documentation/examples on how to assign custom QoS profiles to these nodes?

**Comment by ruimscarvalho98** [comment]
Ok, after digging a bit in the code I found out that the default qos is always assigned in the ROS2 system handle [here](https://github.com/eProsima/ROS2-SH/blob/0ec37df407d0ca4ad47585f8e836c033425641c8/ros2/src/SystemHandle.cpp) (code pasted bellow): 
```
rmw_qos_profile_t parse_rmw_qos_configuration(
        const YAML::Node& /*configuration*/)
{
    // TODO(MXG): Parse the configuration node
    // This is currently considered low-priority
    return rmw_qos_profile_default;
}
```
is there any plan in the near future to add this functionality?

**Comment by lauramg15** [comment]
Good afternoon @ruimscarvalho98,

We have in the roadmap a new feature to configure the ROS 2 QoS. We will inform you when it is ready to use.

**Comment by ruimscarvalho98** [comment]
Ok, thank you for that

**Comment by lauramg15** [comment]
Good morning @ruimscarvalho98,

The feature to modify the ROS 2 QoS is now available to use. The [ROS2-SH Readme](https://github.com/eProsima/ROS2-SH#configuration) explains how to configure the YAML file to use it.

**Comment by ruimscarvalho98** [comment]
Hello @laura-eprosima thanks a lot! I'll add testing this feature to my to-do list

**Comment by lauramg15** [comment]
I am going to close this issue, please reopen it if you have any more problems and we will be happy to help.
