### ISSUE TITLE
Perfect way of installing ROS2-dashing Integration Service on Ubuntu 18.04

### ISSUE THREAD

**Issue by sumitpaulde** [eProsima/Integration-Service#183]
Hi, I have successfully build my ros2 foxy workspace with Fast-RTPS and Integration-Service and it works fine. After that I have tried with ros2-dashing on Ubuntu 18.04 with eProsima-Fast Ratps and Integration-Service. But I am getting lots of build errors which I have no clue of.

As Integration-service has gone through lots of changes (found in the closed issues) so I would like to know the compatibility of Fast-RTPS version and which Integration-service I should use. Old comments mentioned about **soss-rosidl soss-ros2 soss-ros2-test**  but I am unable to find those.

Please suggest me. Thanks a lot.

**Comment by MiguelBarro** [comment]
I'm afraid the minimum ROS2 version supported by Integration Service is foxy. Lower versions may have issues with Fast-DDS deprecated APIs.
