### ISSUE TITLE
Why did I get an error compiling ROS2_SH using "colcon build"

### ISSUE THREAD

**Issue by p-zzg** [eProsima/Integration-Service#184]
cmake has an error, as shown below:

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_c" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_typesupport_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_cpp" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_cpp" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_c" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_typesupport_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_cpp" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_cpp" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_c" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_typesupport_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_cpp" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_cpp" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_c" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_typesupport_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_cpp" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_cpp" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_c" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_typesupport_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_cpp" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_cpp" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_c" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_typesupport_c"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target "std_msgs::std_msgs__rosidl_generator_cpp"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_introspection_cpp" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:75 (add_library):
  Target "is-ros2" links to target
  "std_msgs::std_msgs__rosidl_typesupport_cpp" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

**Comment by MiguelBarro** [comment]
ROS2-SH is since https://github.com/eProsima/Integration-Service/pull/186 successful as attested by CI
