### ISSUE TITLE
ERROR WHILE EXECUTE hello_ros.yaml

### ISSUE THREAD

**Issue by sparkskraps** [eProsima/Integration-Service#21]
I followed the tutorial to let ros1 communicate with ros2,  After build relevant plugin. when i execute the step that (soss src/soss-ros1/examples/hello_ros.yaml), i got the following error message:

soss-ros1 could not find .mix file for message type: std_msgs/String
 -- Make sure that you have generated the soss-ros1 extension for that message type by calling soss_rosidl_mix(PACKAGES <package> MIDDLEWARES ros1) in your build system!
Failed to load middlewares!

I check the source code, but not really figure out the reason. Does anyone happen to know this problem? Thanks.

**Comment by mxgrey** [comment]
I think the instructions on the README may be out of date.

The `soss-ros1` plugin has been put into a [separate repo](https://github.com/osrf/soss-ros1) which must be built in a separate workspace to avoid conflicts between the ROS1 and ROS2 build environments. Once both the `soss` and `soss-ros1` workspaces are built, you'll need to source each one before running the example `hello_ros.yaml` configuration for soss.

I'll try to find time to fix the documentation.

**Comment by sparkskraps** [comment]
Solved my problem, thank you :).
I will close this issue.

**Comment by mxgrey** [comment]
I'll keep this issue open until the documentation is fixed.

Thanks for reporting this!

**Comment by mxgrey** [comment]
It seems the README is correct, so we will close this issue.
