### ISSUE TITLE
【Problem】error when compile soss-ros2-test

### ISSUE THREAD

**Issue by sparkskraps** [eProsima/Integration-Service#22]
When i compile the soss-ros2-test code in a new device(skylake & ubuntu18.04), the terminal output the following error message.
And i follow the tutorials step by step, before execute colcon build, I also remember source /opt/ros/dashing/setup.bash. (i use dashing version of ros2). On those previous device that i used, without this problem.
```
dbt@cscsh-bdk-skylake1:~/rosis/soss$ colcon build --packages-up-to soss-ros2-test
Starting >>> soss-core
Finished <<< soss-core [0.26s]                      
Starting >>> soss-rosidl
Starting >>> soss-mock
Finished <<< soss-rosidl [0.12s]                                                     
Starting >>> soss-ros2
Finished <<< soss-mock [0.16s]                                                            
Finished <<< soss-ros2 [0.17s]                  
Starting >>> soss-ros2-test
--- stderr: soss-ros2-test                         
Traceback (most recent call last):
  File "/home/dbt/rosis/soss/build/soss-ros2-test/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/home/dbt/rosis/soss/build/soss-ros2-test/devel/env.sh')
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/environment_cache.py", line 62, in generate_environment_script
    env_after = ast.literal_eval(output.decode('utf8'))
  File "/usr/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    ROS_DISTRO was set to 'dashing' before. Please make sure that the environment does not mix paths from different distributions.
                 ^
SyntaxError: invalid syntax
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python3
  "/home/dbt/rosis/soss/build/soss-ros2-test/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/all.cmake:207 (safe_execute_process)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  /opt/ros/melodic/share/genmsg/cmake/genmsg-extras.cmake:9 (find_package)
  /opt/ros/melodic/share/genmsg/cmake/genmsgConfig.cmake:199 (include)
  /opt/ros/melodic/share/actionlib_msgs/cmake/actionlib_msgs-extras.cmake:2 (find_package)
  /opt/ros/melodic/share/actionlib_msgs/cmake/actionlib_msgsConfig.cmake:199 (include)
  /opt/ros/melodic/share/nav_msgs/cmake/nav_msgsConfig.cmake:174 (find_package)
  CMakeLists.txt:13 (find_package)


---
Failed   <<< soss-ros2-test	[ Exited with code 1 ]

Summary: 4 packages finished [2.06s]
  1 package failed: soss-ros2-test
  1 package had stderr output: soss-ros2-test
```

Does anybody know what the reason is? or what can i try to solve this problem?
Appreciate.

**Comment by mxgrey** [comment]
It looks like your `ROS1` and `ROS2` build environments are getting cross-contaminated.

I haven't had a chance to update the README yet. Hopefully I'll be able to get to that during or after ROSCon next week. But I've found that the most reliable way to make your build environments clean is to completely isolate the `ROS1` and `ROS2` environments from each other with something like this:

* Have a workspace for all non-ROS soss components:

```
~/rosis/soss$ colcon build --packages-up-to soss-core soss-mock soss-websocket-test
```

* Then a workspace for just the ROS2 components (you can symlink the `~/rosis/soss/src/soss` directory into `~/rosis/soss-ros2/src/`):

```
~/rosis/soss-ros2$ source ~/rosis/soss/install/setup.bash
~/rosis/soss-ros2$ source /opt/ros/dashing/setup.bash
~/rosis/soss-ros2$ colcon build --packages-select soss-rosidl soss-ros2 soss-ros2-test
```

* Then a workspace for just the ROS1 components (containing just the [`soss-ros1` repo](https://github.com/osrf/soss-ros1)):
```
~/rosis/soss-ros1$ source ~/rosis/soss/install/setup.bash
~/rosis/soss-ros1$ source /opt/ros/melodic/setup.bash
~/rosis/soss-ros1$ colcon build --packages-up-to soss-ros1-test
```

After that, you should be able to source both the `soss-ros1` and `soss-ros2` workspaces to run a `soss` instance that bridges `ROS1` and `ROS2`.

I'm thinking about splitting `soss-ros2` out into its own repo to make this procedure cleaner. If anyone has opinions on that idea, do share.

**Comment by jamoralp** [comment]
Good morning,

I am closing this, since there was not activity for a very long time. Anyway, as mentioned above, this seems to be related to the fact that you were sourcing ROS 1 to compile the *ROS 2 System Handle*. If that is the case, please have a look at an example on how to make them coexist and communicate, using *Integration Service*: https://integration-service.docs.eprosima.com/en/latest/examples/different_protocols/pubsub/ros1-ros2.html
