### ISSUE TITLE
Websocket package build failed

### ISSUE THREAD

**Issue by RenjilaRajan** [eProsima/Integration-Service#33]
I tried the following steps in building SOSS
$ cd ~
$ mkdir -p workspaces/soss
$ cd workspaces/soss
$ git clone http://github.com/osrf/soss_v2 src/soss
source /opt/ros/eloquent/setup.bash
colcon build

The  build failed with the following error.
Starting >>> soss-websocket
--- stderr: soss-websocket                         
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "Findwebsocketpp.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "websocketpp", but CMake did not find one.

  Could not find a package configuration file provided by "websocketpp" with
  any of the following names:

    websocketppConfig.cmake
    websocketpp-config.cmake

  Add the installation prefix of "websocketpp" to CMAKE_PREFIX_PATH or set
  "websocketpp_DIR" to a directory containing one of the above files.  If
  "websocketpp" provides a separate development package or SDK, be sure it
  has been installed.
Please let me know how to fix this

**Comment by mxgrey** [comment]
cmake is telling you that you're missing `libwebsocketpp-dev`.

If you're using Ubuntu, you can install it with this command:

```
sudo apt install libwebsocketpp-dev
```

**Comment by 0RE0NE0** [comment]
> cmake is telling you that you're missing `libwebsocketpp-dev`.
> 
> If you're using Ubuntu, you can install it with this command:
> 
> ```
> sudo apt install libwebsocketpp-dev
> ```

Hey, I know its long ago but I'm on windows (Win 11 23H2, VS 2017, VCPKG 2024-08-01) and got the same error, i installed websocketpp via vcpkg. Do you happen to know the error here? because i dont think i'm missing an linux lib, or do i?

Here is my CMakeList, hop you  can help me xD
```
cmake_minimum_required(VERSION 3.10)
project(WebSocketSystem)

SET(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "C:/Users/Admin/OneDrive/Development/WebSocketSystem/vcpkg_installed/x64-windows/include")
SET(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "C:/Users/Admin/OneDrive/Development/WebSocketSystem/vcpkg_installed/x64-windows/lib")


include_directories("C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um")
include_directories("C:/Users/Admin/OneDrive/Development/WebSocketSystem/vcpkg_installed/x64-windows/include")
include_directories("C:/Users/Admin/OneDrive/Development/WebSocketSystem/vcpkg_installed/x64-windows/include/**")
include_directories("C:/Users/Admin/OneDrive/Development/WebSocketSystem/vcpkg_installed/x64-windows/include/lib")
include_directories("C:/Users/Admin/OneDrive/Development/WebSocketSystem/vcpkg_installed/x64-windows/include/lib/**")


find_package(Boost REQUIRED)
find_package(websocketpp REQUIRED)

add_executable(websocket_example main.cpp)
target_link_libraries(websocket_example PRIVATE websocketpp::websocketpp)
target_link_libraries(websocket_example PRIVATE Boost::boost websocketpp)
```
