### ISSUE TITLE
Wrong formatted json in websocket service request causes SEGFAULT

### ISSUE THREAD

**Issue by janandries** [eProsima/Integration-Service#35]
I'm running a websocket-server<->ros2 bridge where I run into SEGFAULTs if the send websocket messages is not exactly well formatted. 

I have a service that consists of a single _uint8_ parameter for the request, and a _uint8[], bool_ and _string_ as response:

```
#robot_service_interfaces/ReadByte.srv:
uint8 count 1 # The number of bytes to read
---
uint8[] data  # Bytes read
bool success  # indicate successful run of triggered service
string message  # informational, e.g. for error messages
```

When the client sends out a request with a string type parameter:
```
{"op":"call_service","service":"robot_service_interface/read_bytes","args":{"count":"1"}}
```
this request is propagated to the ros2-idl where it causes a segfault in `soss-core/include/utilities.hpp`, on line 282:
```
  // Documentation inherited from Convert
  static void from_soss_field(const const_field_iterator& from, native_type& to)
  {
SEGFAULT >>>>   to = static_cast<native_type>(*from->second.cast<soss_type>());
  }
```

(if of any use, here is the call-stack)
[callstackLibsoss-rosidl.txt](https://github.com/osrf/soss/files/4673265/callstackLibsoss-rosidl.txt)

To pass the value as a string is of course not correct, but soss-websocket should catch this and not pass it on to `ros-idl` imho.

Another similar issue is that for int16 type making a service request always causes a Segfault, but this might have to do more with ros_idl handling of dictionaries. For the following service interface:
```
int16 STOP_NONE        = 0  # This command effectively does nothing
int16 STOP_IMMEDIATELY = 1  # Stop the robot as soon as possible without waiting for checkpoints.
int16 STOP_AFTER_BEAD  = 2  # Stop the robot after the current bead.
int16 STOP_AFTER_LAYER = 3  # Stop the robot after the current layer.
int16 STOP_RESET       = 4  # Reset all stop signals to cleared state.

int16 command  # Robot stop command {STOP_NONE, STOP_IMMEDIATELY, STOP_AFTER_BEAD, STOP_AFTER_LAYER}
---
bool success  # indicate successful run of triggered service
string message  # informational, e.g. for error messages
```
I can succesfully call from ROS with string value `ros2 service call /robot_service_interface/stop robot_service_interfaces/srv/Stop "{'command':'1'}"` or int value `ros2 service call /robot_service_interface/stop robot_service_interfaces/srv/Stop "{'command':1}"` 
(I would expect that `"{'command':STOP_NONE}"`) should also work, but i receive `Failed to populate field: invalid literal for int() with base 10: 'STOP_NONE'`)

However, when called through `soss-websocket` I always get a Segfault, no matter if I use a int value:
```
{"op":"call_service","service":"robot_service_interface/stop","args":{"command":"1"}}
^SEGFAULT
{"op":"call_service","service":"robot_service_interface/stop","args":{"command":1}}
^SEGFAULT
```

**Comment by mxgrey** [comment]
> To pass the value as a string is of course not correct, but soss-websocket should catch this and not pass it on to ros-idl imho.

We agree, and we intend to fix this with [xtypes](https://github.com/osrf/soss/pull/20) in the next revision of soss. With the introduction of xtypes, the middlewares will be able to communicate to each other about what type of information they're expecting, and then this kind of issue should be resolved automatically. The current implementation is naive, and it trusts both ends of the connection to do everything perfectly, which is of course not a reasonable expectation for all cases.

> (I would expect that "{'command':STOP_NONE}") should also work, but i receive Failed to populate field: invalid literal for int() with base 10: 'STOP_NONE')

I think it's much less clear where the responsibility lies in this use case. I don't think it's necessarily reasonable to expect the `soss-ros2` plugin to attempt to always try to interpret string values as possibly referring to predefined constant values. The `ros2` CLI tool was specifically made for this kind of human user convenience, whereas soss is meant to tie automated systems together; not be a human interface. It's certainly possible to give this feature to a `soss-ros2` plugin, and you as a user can always implement your own flavor of a `soss-ros2` plugin that can do this. It's just not clear to me that it's an appropriate feature to officially support for this tool.

**Comment by janandries** [comment]
good to see something is in the pipeline to make this a more solid library.

**Comment by jamoralp** [comment]
Hello, this has been solved in https://github.com/eProsima/WebSocket-SH/pull/26 and https://github.com/eProsima/Integration-Service/pull/149. Please wait until this is merged, then try and reopen this issue if the problem persists
