### ISSUE TITLE
Segfault issues 

### ISSUE THREAD

**Issue by matthijsramlab** [eProsima/Integration-Service#38]
I am getting allot segfaults when sending a service request... 

```
Segmentation fault (core dumped)
``` 

At first I tried to send a int8 (as defined in the srv message), this caused a segfault. One of the other calls I made did work, so I wondered why... The other call uses an uint8. So I changed it to an uint8, and now this problem is solved. Do wonder why you need to use a uint8?

Now I am trying to send a string in one of the service calls, however none of the message types work. I tried:

string
wstring 
char

These all give segfaults..... 

When I replace it with an uint8 and send a number, it works.

**Comment by jamoralp** [comment]
I am closing since this has been inactive for a long time and no descriptive information is provided. Please reopen and specify information about your use case if it still happens, so that we can help you better :slightly_smiling_face:
