### ISSUE TITLE
Feature request: MQTT integration

### ISSUE THREAD

**Issue by fkromer** [eProsima/Integration-Service#46]
Would be great if one could integrate via [ROS2-Integration-Service](https://github.com/eProsima/ROS2-Integration-Service) and *soss* with MQTT. What do you guys think? From a high level view it should be possible to integrate *ROS2 topics <-> MQTT topics*.

**Comment by mxgrey** [comment]
Having an MQTT plugin would be great, but we're constrained by our available human resources and funding obligations, so I don't anticipate we'll be working on this at OSRC until it becomes a requirement for one of our contracts.

That being said, we'd be happy to review and merge a Pull Request that adds this feature. Alternatively it could be developed in its own repo, and we could just link to it from the `soss` README.

**Comment by fkromer** [comment]
Sure. I've created this issue because we will probably be interested in cooperation (e.g. funding based source code contribution). However if we can do that is in clarification ATM.
