### ISSUE TITLE
Documentation is out of date and inaccurate

### ISSUE THREAD

**Issue by gc-robotics** [eProsima/Integration-Service#80]
Hi. 

Referring to this and few other links to install IS:
https://www.rosin-project.eu/ftp/ros2-integration-service

the SOSS_V2, SOSS_DSS repos do not exist anymore and cannot be found. 

Could you please provide updated instructions? 

Thanks in advance.

**Comment by jamoralp** [comment]
Hello, yes, sorry. The SOSS product was completely transferred to eProsima and we renamed it to Integration Service. We have been working on a brand new documentation that can be found [here](https://integration-service.docs.eprosima.com/en/latest/). There you can find lots of examples and instructions on how to build and use the Integration Service.

Also, we are working on completing this documentation by means of adding service server <-> client examples and also a full API reference of the product suite (the Integration Service Core + all system handles). Please feel free to add any commentaries or changes that you think might be needed to improve the documentation. The source code repository for it can be found at https://github.com/eProsima/Integration-Service-docs.

Finally, if you think this issue has already been solved, please close this issue. Thanks!

**Comment by jamoralp** [comment]
Closing since documentation was updated two weeks ago and has been continuosly updated since then.
